version: '3.7'

services:
  grafana:
    image: grafana/grafana:7.5.7
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "1"
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: {{ passwords.grafana_admin }}
      GRAFANA_TIMESCALE_READER_PASSWORD: {{ passwords.grafanareader }}
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      - monitoring
    volumes:
      - /etc/pytorch/grafana:/var/lib/grafana
      - /etc/pytorch/grafana-provisioning/:/etc/grafana/provisioning

  timescaledb:
    image: timescale/timescaledb:2.3.0-pg12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: {{ passwords.timescaledb }}
      PG_PASSWORD: {{ passwords.timescaledb }}
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      - monitoring
    volumes:
      - /etc/pytorch/timescaledb:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:v2.27.1
    ports:
      - 9090:9090
    networks:
      - monitoring
    volumes:
      - /etc/pytorch/prometheus.yml:/etc/prometheus/prometheus.yml

  promscale:
    image: timescale/promscale:latest
    ports:
      - 9201:9201
    restart: on-failure
    depends_on:
      - timescaledb
      - prometheus
    networks:
      - monitoring
    environment:
      PROMSCALE_DB_CONNECT_RETRIES: 10
      PROMSCALE_WEB_TELEMETRY_PATH: /metrics-text
      PROMSCALE_DB_URI: postgres://postgres:{{ passwords.timescaledb }}@timescaledb:5432/postgres?sslmode=allow

  nginx:
    image: nginx:1.21.0
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      - monitoring
    volumes:
        - "/etc/pytorch/http.conf:/etc/nginx/conf.d/default.conf"
        - "/etc/pytorch/nginx.conf:/etc/nginx/nginx.conf"
        - "/etc/pytorch/fullchain.pem:/etc/nginx/fullchain.pem"
        - "/etc/pytorch/privkey.pem:/etc/nginx/privkey.pem"

networks:
  monitoring:
    external: true
