name: Build Linux Conda

on:
  workflow_call:
    inputs:
      domain:
        description: 'name of the domain library calling this reusable workflow.'
        required: true
        type: string
      docker_image:
        description: 'docker image container for running the reusable workflow.'
        required: true
        type: string
      python_version:
        description: 'python version to use for building conda binary'
        required: true
        type: string
      gpu_arch_version:
        description: 'cuda version to use for building conda binary'
        required: true
        type: string

jobs:
  conda:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: ${{ inputs.python_version }}
      PACKAGE_TYPE: conda
      DOMAIN: ${{ inputs.domain }}
      GPU_ARCH_VERSION: ${{ inputs.gpu_arch_version }}
    container:
      image: ${{ inputs.docker_image }}
    steps:
    - name: Checkout the repository  
      uses: actions/checkout@v2
    - name: Set artifact name
      run: |
        echo "ARTIFACT_NAME=${DOMAIN/\//_}_${REF}_${PYTHON_VERSION}" >> "${GITHUB_ENV}"
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        installer-url: https://github.com/conda-forge/miniforge/releases/download/4.8.3-2/Miniforge-pypy3-4.8.3-2-Linux-x86_64.sh
        auto-update-conda: true
        python-version: ${{ inputs.python_version }}
        activate-environment: build
    - name: Clean conda environment
      run: |
        conda clean --all --quiet --yes
    - name: Create conda environment
      run: |
        CONDA_ENV="${RUNNER_TEMP}/conda_environment_${GITHUB_RUN_ID}"
        conda create \
          --yes \
          --prefix "${CONDA_ENV}" \
          "python=${PYTHON_VERSION}" \
          cmake=3.22 \
          ninja=1.10 \
          numpy=1.23 \
          pkg-config=0.29 \
          wheel=0.37
        echo "CONDA_ENV=${CONDA_ENV}" >> "${GITHUB_ENV}"
        echo "CONDA_RUN=conda run -p ${CONDA_ENV}" >> "${GITHUB_ENV}"
    - name: Install pytorch-pkg-helpers
      run: |
        ${CONDA_RUN} python3 -m pip install pytorch-pkg-helpers==0.1.0
    - name: Create environemnt variables from pytorch-pkg-helpers
      run: |
        # https://github.com/actions/checkout/issues/760#issuecomment-1097501613
        # need to move this version.py get_root_dir(), and make it generic for all repositories
        git config --global --add safe.directory /__w/audio/audio
        BUILD_ENV_FILE="${RUNNER_TEMP}/build_env_${GITHUB_RUN_ID}"
        ${CONDA_RUN} python3 -m pytorch_pkg_helpers > "${BUILD_ENV_FILE}"
        echo "BUILD_ENV_FILE=${BUILD_ENV_FILE}" >> "${GITHUB_ENV}"
      # Using the wheel pre-script since I suspect it will be the same
    - name: Run pre-build script
      run: ./packaging/pre_build_script_wheel.sh
    - name: Generate Conda Recipe Path
      run: |
        echo "CONDA_PATH=packaging/${{ inputs.domain }}" >> "{GITHUB_ENV}"
        echo "CUDATOOLKIT_CHANNEL=nvidia" >> "{GITHUB_ENV}"
        echo "CONDA_CHANNEL_FLAGS= -c pytorch-nightly" >> "{GITHUB_ENV}"
    - name: Build Conda Package
      run: conda build -c defaults \
              -c "${{ env.cudatoolkit_channel }}" "${{ env.conda_channel_flags }}" \
              --no-anaconda-upload \
              --python "${{ env.python_version }}" \
              "${{ env.conda_path }}" 
    - name: Run post-build script
      run: ./packaging/post_build_script_wheel.sh
