name: Build Linux Conda

on:
  workflow_call:
    inputs:
      domain:
        description: 'name of the domain library calling this reusable workflow.'
        required: true
        type: string
      image:
        description: 'docker image container for running the reusable workflow.'
        required: false
        type: string

jobs:
  wheels:
    runs-on: ubuntu-latest
    steps:
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        installer-url: https://github.com/conda-forge/miniforge/releases/download/4.8.3-2/Miniforge-pypy3-4.8.3-2-Linux-x86_64.sh
        auto-update-conda: true
        python-version: 3.8
        activate-environment: build
    - name: Clean conda environment
      run: |
        conda clean --all --quiet --yes
    - name: Install conda build
      run: |
        conda install conda-build
    - uses: actions/checkout@v2
    - name: Run pre-build script
      run: ./packaging/pre_build_script_conda.sh
    - name: Generate Conda Recipe Path
      run: export CONDA_PATH=packaging/${{ inputs.domain }}
    - name: Build Conda Package
      run: conda build -c defaults \
              -c "$CUDATOOLKIT_CHANNEL" "${CONDA_CHANNEL_FLAGS:-}" \
              --no-anaconda-upload \
              --python "$PYTHON_VERSION" \
              "$CONDA_PATH" 
    - name: Run post-build script
      run: ./packaging/post_build_script_conda.sh
