name: Check Alerts
on:
  schedule:
    # Every 5 minutes
    - cron: "*/5 * * * *"
  # Have the ability to trigger this job manually through the API

  workflow_dispatch:
  pull_request:


jobs:
  update-disabled-tests:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install requests
        run: |
           pip install requests
      - name: Check for alerts and creates issue
        run: |
          python3 torchci/scripts/check_alerts.py
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
