name: Check Alerts
on:
  schedule:
    # Every 5 minutes
    - cron: "*/5 * * * *"
  # Have the ability to trigger this job manually through the API
  workflow_dispatch:

jobs:
  update-disabled-tests:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate new disabled test json
        run: |
          .github/scripts/check_alerts.py
