name: stronghold

on:
  pull_request:
    paths:
      - .github/workflows/stronghold.yml
      - tools/stronghold/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/stronghold.yml
      - tools/stronghold/**

jobs:
  black:
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      script: |
        echo ::group::setup Python environment
        cd tools/stronghold/
        python -m venv .venv/
        source .venv/bin/activate
        pip install --requirement=requirements.txt
        echo ::endgroup::

        black --check --diff .

  flake8:
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      script: |
        echo ::group::setup Python environment
        cd tools/stronghold/
        python -m venv .venv/
        source .venv/bin/activate
        pip install --requirement=requirements.txt
        echo ::endgroup::

        flake8 .

  mypy:
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      script: |
        echo ::group::setup Python environment
        cd tools/stronghold/
        python -m venv .venv/
        source .venv/bin/activate
        pip install --requirement=requirements.txt
        echo ::endgroup::

        mypy .

  pytest:
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      script: |
        echo ::group::setup Python environment
        cd tools/stronghold/
        python -m venv .venv/
        source .venv/bin/activate
        pip install --requirement=requirements.txt
        echo ::endgroup::

        pytest
