name: stronghold

on:
  pull_request:
    paths:
      - .github/workflows/stronghold.yml
      - tools/stronghold/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/stronghold.yml
      - tools/stronghold/**

jobs:
  api-compatibility-check:
    uses: ./.github/workflows/linux_job.yml
    with:
      # Fetch the commit, rather than the merge.
      ref: ${{ github.event.pull_request.head.sha }}
      script: |
        cd tools/stronghold/
        bin/build-check-api-compatibility
        # We need to fetch the base otherwise, we can't diff against it.
        git fetch origin ${{ github.event.pull_request.base.sha }}
        bin/check-api-compatibility                              \
            --base-commit=${{ github.event.pull_request.base.sha }} \
            --head-commit=${{ github.event.pull_request.head.sha }}

      docker-image: debian:bullseye

  black:
    uses: ./.github/workflows/linux_job.yml
    with:
      script: |
        echo ::group::setup Python environment
        cd tools/stronghold/
        python -m venv .venv/
        source .venv/bin/activate
        pip install --requirement=requirements.txt
        echo ::endgroup::

        black --check --diff .

      docker-image: python:3.11.0-slim-bullseye

  flake8:
    uses: ./.github/workflows/linux_job.yml
    with:
      script: |
        echo ::group::setup Python environment
        cd tools/stronghold/
        python -m venv .venv/
        source .venv/bin/activate
        pip install --requirement=requirements.txt
        echo ::endgroup::

        flake8 .

      docker-image: python:3.11.0-slim-bullseye

  mypy:
    uses: ./.github/workflows/linux_job.yml
    with:
      script: |
        echo ::group::setup Python environment
        cd tools/stronghold/
        python -m venv .venv/
        source .venv/bin/activate
        pip install --requirement=requirements.txt
        echo ::endgroup::

        mypy .

      docker-image: python:3.11.0-slim-bullseye

  pytest:
    uses: ./.github/workflows/linux_job.yml
    with:
      script: |
        echo ::group::setup Python environment
        cd tools/stronghold/
        python -m venv .venv/
        source .venv/bin/activate
        pip install --requirement=requirements.txt
        echo ::endgroup::

        pytest

      docker-image: debian:bullseye
